language: node_js

node_js:
  - "8.11.0"

cache:
  directories:
    - elm-stuff/

before_install:
  - if [ ${TRAVIS_OS_NAME} == "osx" ];
    then brew update; brew install nvm; mkdir ~/.nvm; export NVM_DIR=~/.nvm; source $(brew --prefix nvm)/nvm.sh;
    fi
install:
  - npm install -g elm elm-test@0.19.0-beta9

script: elm-test
